"""Document ingestion and hybrid retrieval for the support knowledge base.

The application intentionally has no mandatory vector-database dependency.  This
module provides a durable, deterministic local index (sparse TF-IDF + keyword
matching) and an optional dense-vector layer.  A remote or local embedding model
can be plugged in through :class:`EmbeddingProvider`; the built-in
``HashEmbeddingProvider`` keeps the demo useful when no model package is
installed.

The public API is deliberately small::

    index = PersistentHybridIndex(Path("data"))
    index.rebuild()                 # or ``index.build()`` for incremental use
    hits = index.search("滚刷缠绕怎么办", top_k=5)
    context, citations = index.context("滚刷缠绕怎么办")

Every hit carries a stable chunk id and citation metadata (source file, page,
chunk number and character offsets), so generated answers can be audited.
Index files are JSON and are written atomically.  They are runtime artifacts;
callers can put ``index_dir`` in ``.gitignore`` rather than committing them.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import importlib.util
import json
import math
import os
import re
import tempfile
import time
import unicodedata
from collections import Counter, defaultdict
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol, runtime_checkable


INDEX_VERSION = 1
# Bump this marker when the tokenisation/chunking/index semantics change in a
# way that cannot be represented by the individual configuration fields below.
# Keeping it separate from ``INDEX_VERSION`` lets us add compatibility checks
# without invalidating callers that only inspect the persisted format version.
INDEX_CONFIG_VERSION = 1
DEFAULT_EXTENSIONS = frozenset({".txt", ".pdf"})
_TOKEN_RE = re.compile(r"[a-zA-Z][a-zA-Z0-9_+#.-]*|\d+(?:[.,:/%-]\d+)*")
_CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]+")

# A deliberately conservative list.  Removing common function words improves
# ranking while retaining product terms such as ``不`` and ``没有`` that change
# the meaning of a support question.
_STOPWORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "how",
        "i",
        "in",
        "is",
        "it",
        "of",
        "on",
        "or",
        "the",
        "to",
        "what",
        "when",
        "where",
        "which",
        "with",
        "的",
        "了",
        "呢",
        "吗",
        "啊",
        "请",
        "如何",
        "怎么",
        "怎样",
        "可以",
        "是否",
        "一个",
        "这个",
    }
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _normalise_text(value: str) -> str:
    value = unicodedata.normalize("NFKC", value).replace("\x00", "")
    # Keep line boundaries (the chunker uses them) but collapse pathological
    # whitespace generated by PDF extraction.
    value = re.sub(r"[ \t\f\v]+", " ", value)
    value = re.sub(r"\n{3,}", "\n\n", value)
    return value.strip()


def tokenize(value: str, *, include_unigrams: bool = True) -> list[str]:
    """Tokenise Chinese and Latin text without requiring jieba.

    Latin words/numbers are kept as whole tokens.  Chinese runs contribute
    overlapping bigrams (and optionally unigrams), plus the full run for exact
    product names.  This gives useful recall for both ``尘盒`` and
    ``尘盒容量`` while remaining deterministic and very fast.
    """

    value = unicodedata.normalize("NFKC", value).lower()
    tokens: list[str] = []
    for match in _TOKEN_RE.finditer(value):
        token = match.group(0).strip("._-+")
        if token and token not in _STOPWORDS:
            tokens.append(token)
    for match in _CJK_RE.finditer(value):
        run = match.group(0)
        if run in _STOPWORDS:
            continue
        if include_unigrams:
            tokens.extend(ch for ch in run if ch not in _STOPWORDS)
        if len(run) > 1:
            tokens.extend(run[i : i + 2] for i in range(len(run) - 1))
        # Full runs are useful for named modes/model numbers, but cap their
        # length so a long paragraph cannot become one giant vocabulary item.
        if len(run) <= 16:
            tokens.append(run)
    return tokens


@dataclass(frozen=True)
class PageText:
    """Text extracted from one logical page (or a TXT pseudo-page)."""

    text: str
    page: int | None = None
    parser: str = "text"


@dataclass(frozen=True)
class DocumentChunk:
    """A retrievable chunk and its provenance metadata."""

    id: str
    source: str
    content: str
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def page(self) -> int | None:
        value = self.metadata.get("page")
        return int(value) if isinstance(value, int) else None

    @property
    def citation(self) -> str:
        page = self.page
        suffix = f" p.{page}" if page else ""
        chunk_index = self.metadata.get("chunk_index")
        if chunk_index is not None:
            suffix += f" §{int(chunk_index) + 1}"
        return f"{self.source}{suffix}"

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "source": self.source,
            "content": self.content,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "DocumentChunk":
        return cls(
            id=str(value["id"]),
            source=str(value["source"]),
            content=str(value["content"]),
            metadata=dict(value.get("metadata") or {}),
        )


@dataclass(frozen=True)
class RetrievalHit:
    """Search result with component scores and citation metadata."""

    chunk: DocumentChunk
    score: float
    lexical_score: float = 0.0
    keyword_score: float = 0.0
    vector_score: float = 0.0
    rank: int = 0

    # Compatibility conveniences for the existing ``KnowledgeHit`` shape.
    @property
    def id(self) -> str:
        return self.chunk.id

    @property
    def source(self) -> str:
        return self.chunk.source

    @property
    def content(self) -> str:
        return self.chunk.content

    @property
    def citation(self) -> str:
        return self.chunk.citation

    def as_dict(self, *, excerpt_chars: int = 400) -> dict[str, Any]:
        return {
            "id": self.id,
            "source": self.source,
            "content": self.content,
            "excerpt": self.content[:excerpt_chars],
            "citation": self.citation,
            "score": round(float(self.score), 6),
            "lexical_score": round(float(self.lexical_score), 6),
            "keyword_score": round(float(self.keyword_score), 6),
            "vector_score": round(float(self.vector_score), 6),
            "metadata": dict(self.chunk.metadata),
        }


@runtime_checkable
class EmbeddingProvider(Protocol):
    """Protocol for optional dense embeddings.

    Implementations may expose either ``embed_documents`` and ``embed_query``
    or a single callable accepting a sequence of strings.  The index validates
    dimensions and normalises vectors before persisting them.
    """

    def embed_documents(self, texts: Sequence[str]) -> Sequence[Sequence[float]]: ...

    def embed_query(self, text: str) -> Sequence[float]: ...


class HashEmbeddingProvider:
    """Dependency-free, deterministic dense vectors.

    This is a feature-hashing encoder rather than a language model.  It gives a
    stable vector retrieval baseline for the demo and can be replaced with a
    multilingual sentence-transformer or DashScope provider in production.
    """

    def __init__(self, dimensions: int = 384) -> None:
        if dimensions < 16:
            raise ValueError("dimensions must be at least 16")
        self.dimensions = dimensions

    def _embed(self, text: str) -> list[float]:
        vector = [0.0] * self.dimensions
        tokens = tokenize(text)
        if not tokens:
            return vector
        for token in tokens:
            digest = hashlib.blake2b(token.encode("utf-8"), digest_size=16).digest()
            index = int.from_bytes(digest[:8], "big") % self.dimensions
            sign = 1.0 if digest[8] & 1 else -1.0
            # A tiny sub-weight for token length helps distinguish model names
            # while avoiding a dominant long-token feature.
            vector[index] += sign * (1.0 + min(len(token), 12) / 24.0)
        norm = math.sqrt(sum(item * item for item in vector))
        if norm:
            vector = [item / norm for item in vector]
        return vector

    def embed_documents(self, texts: Sequence[str]) -> list[list[float]]:
        return [self._embed(text) for text in texts]

    def embed_query(self, text: str) -> list[float]:
        return self._embed(text)


class SentenceTransformerProvider:
    """Lazy optional adapter for ``sentence-transformers``.

    Importing this class never imports the optional package.  A clear error is
    raised only when the provider is instantiated without the dependency.
    """

    def __init__(self, model_name: str = "paraphrase-multilingual-MiniLM-L12-v2") -> None:
        try:
            from sentence_transformers import SentenceTransformer  # type: ignore
        except ImportError as exc:  # pragma: no cover - depends on environment
            raise RuntimeError(
                "sentence-transformers is not installed; use HashEmbeddingProvider "
                "or install the optional vector dependencies"
            ) from exc
        self.model_name = model_name
        self._model = SentenceTransformer(model_name)

    def embed_documents(self, texts: Sequence[str]) -> list[list[float]]:
        vectors = self._model.encode(list(texts), normalize_embeddings=True)
        return [list(map(float, row)) for row in vectors]

    def embed_query(self, text: str) -> list[float]:
        vector = self._model.encode([text], normalize_embeddings=True)[0]
        return list(map(float, vector))


class DashScopeEmbeddingProvider:
    """Optional DashScope/OpenAI-compatible embedding adapter.

    DashScope's embedding endpoint is compatible with ``POST /embeddings``.
    The adapter is intentionally opt-in: constructing it does not make a
    network request, and failures during indexing are handled by the index's
    lexical fallback.  ``DASHSCOPE_API_KEY`` is read from the environment when
    ``api_key`` is omitted, never persisted to the index file.
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        model: str | None = None,
        base_url: str | None = None,
        batch_size: int = 16,
        timeout: float = 20.0,
        retries: int = 2,
    ) -> None:
        self.api_key = api_key if api_key is not None else os.getenv("DASHSCOPE_API_KEY", "")
        self.model = model or os.getenv("DASHSCOPE_EMBEDDING_MODEL", "text-embedding-v3")
        self.base_url = (base_url or os.getenv(
            "DASHSCOPE_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1"
        )).rstrip("/")
        self.batch_size = max(1, int(batch_size))
        self.timeout = max(1.0, float(timeout))
        self.retries = max(0, int(retries))

    @property
    def configured(self) -> bool:
        return bool(self.api_key)

    def _request(self, texts: Sequence[str]) -> list[list[float]]:
        if not self.configured:
            raise RuntimeError("DASHSCOPE_API_KEY is not configured")
        try:
            import httpx  # type: ignore
        except ImportError as exc:  # pragma: no cover - backend requires httpx
            raise RuntimeError("httpx is required for DashScope embeddings") from exc
        payload = {"model": self.model, "input": list(texts)}
        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        last_error: Exception | None = None
        for attempt in range(self.retries + 1):
            try:
                with httpx.Client(timeout=self.timeout) as client:
                    response = client.post(f"{self.base_url}/embeddings", json=payload, headers=headers)
                    response.raise_for_status()
                    body = response.json()
                rows = body.get("data") if isinstance(body, Mapping) else None
                if not isinstance(rows, list):
                    raise RuntimeError("DashScope embedding response has no data array")
                ordered = sorted(rows, key=lambda row: int(row.get("index", 0)) if isinstance(row, Mapping) else 0)
                vectors = [row.get("embedding") for row in ordered if isinstance(row, Mapping)]
                if len(vectors) != len(texts) or any(not isinstance(vector, Sequence) for vector in vectors):
                    raise RuntimeError("DashScope embedding response length mismatch")
                return [_normalise_vector(vector) for vector in vectors]  # type: ignore[arg-type]
            except Exception as exc:  # retry transient provider/transport failures
                last_error = exc
                if attempt < self.retries:
                    time.sleep(min(2.0, 0.25 * (2**attempt)))
        raise RuntimeError(f"DashScope embedding request failed: {last_error}") from last_error

    def embed_documents(self, texts: Sequence[str]) -> list[list[float]]:
        values = list(texts)
        vectors: list[list[float]] = []
        for start in range(0, len(values), self.batch_size):
            vectors.extend(self._request(values[start : start + self.batch_size]))
        return vectors

    def embed_query(self, text: str) -> list[float]:
        return self._request([text])[0]


class DocumentParser:
    """Extract text from TXT and PDF files with graceful optional fallbacks."""

    _TEXT_ENCODINGS = ("utf-8-sig", "utf-8", "gb18030", "big5", "latin-1")

    def parse(self, path: Path) -> list[PageText]:
        suffix = path.suffix.lower()
        if suffix == ".pdf":
            return self._parse_pdf(path)
        return self._parse_text(path)

    def _parse_text(self, path: Path) -> list[PageText]:
        data = path.read_bytes()
        text = ""
        for encoding in self._TEXT_ENCODINGS:
            try:
                text = data.decode(encoding)
                break
            except UnicodeDecodeError:
                continue
        if not text:
            return []
        text = _normalise_text(text)
        return [PageText(text=text, parser="text")] if text else []

    def _parse_pdf(self, path: Path) -> list[PageText]:
        # PyMuPDF is the preferred parser: it preserves page boundaries and is
        # substantially more tolerant of malformed real-world PDFs.
        try:
            import fitz  # type: ignore

            pages: list[PageText] = []
            with fitz.open(path) as document:
                for number, page in enumerate(document, start=1):
                    text = _normalise_text(page.get_text("text") or "")
                    if text:
                        pages.append(PageText(text=text, page=number, parser="pymupdf"))
            if pages:
                return pages
        except Exception:
            pass

        # pypdf/PyPDF2 fallback keeps installations lightweight while allowing
        # users to opt into a parser through requirements.txt.
        for module_name in ("pypdf", "PyPDF2"):
            try:
                module = __import__(module_name)
                reader_cls = getattr(module, "PdfReader", None) or getattr(module, "PdfFileReader", None)
                if reader_cls is None:
                    continue
                reader = reader_cls(str(path))
                raw_pages = getattr(reader, "pages", None)
                if raw_pages is None:
                    raw_pages = [reader.getPage(index) for index in range(int(reader.getNumPages()))]
                pages = []
                for number, page in enumerate(raw_pages, start=1):
                    try:
                        text = _normalise_text(page.extract_text() or "")
                    except Exception:
                        text = ""
                    if text:
                        pages.append(PageText(text=text, page=number, parser=module_name))
                if pages:
                    return pages
            except Exception:
                continue
        return []


class TextChunker:
    """Page-aware, boundary-sensitive character chunker."""

    def __init__(self, chunk_size: int = 900, overlap: int = 120, min_chunk_size: int = 40) -> None:
        if chunk_size <= 0:
            raise ValueError("chunk_size must be positive")
        if overlap < 0 or overlap >= chunk_size:
            raise ValueError("overlap must be >= 0 and smaller than chunk_size")
        self.chunk_size = chunk_size
        self.overlap = overlap
        self.min_chunk_size = max(1, min_chunk_size)

    def chunk_pages(
        self,
        pages: Sequence[PageText],
        *,
        source: str,
        file_hash: str,
        title: str | None = None,
    ) -> list[DocumentChunk]:
        chunks: list[DocumentChunk] = []
        for page in pages:
            text = _normalise_text(page.text)
            if not text:
                continue
            for chunk_index, (content, start, end) in enumerate(self._chunk_text(text)):
                if len(content) < self.min_chunk_size and chunks and page.page == chunks[-1].metadata.get("page"):
                    # Merge tiny trailing fragments into the previous chunk on
                    # the same page; this avoids low-information citations.
                    previous = chunks[-1]
                    merged = f"{previous.content}\n{content}".strip()
                    metadata = dict(previous.metadata)
                    metadata["char_end"] = end
                    chunks[-1] = DocumentChunk(previous.id, previous.source, merged, metadata)
                    continue
                metadata: dict[str, Any] = {
                    "page": page.page,
                    "chunk_index": chunk_index,
                    "char_start": start,
                    "char_end": end,
                    "file_hash": file_hash,
                    "parser": page.parser,
                }
                if title:
                    metadata["title"] = title
                stable = f"{source}:{page.page or 0}:{chunk_index}:{start}:{file_hash}"
                chunk_id = hashlib.sha1(stable.encode("utf-8")).hexdigest()[:20]
                chunks.append(DocumentChunk(chunk_id, source, content, metadata))
        return chunks

    def _chunk_text(self, text: str) -> Iterator[tuple[str, int, int]]:
        if len(text) <= self.chunk_size:
            yield text, 0, len(text)
            return
        start = 0
        text_len = len(text)
        while start < text_len:
            hard_end = min(start + self.chunk_size, text_len)
            end = hard_end
            if hard_end < text_len:
                # Prefer paragraph/sentence boundaries in the final 30% of the
                # window.  If none exist, use the hard limit.
                floor = start + max(1, int(self.chunk_size * 0.70))
                candidates = [
                    text.rfind(marker, floor, hard_end)
                    for marker in ("\n\n", "\n", "。", "！", "？", ". ", "! ", "? ", "; ", "；")
                ]
                boundary = max(candidates, default=-1)
                if boundary >= floor:
                    end = boundary + (2 if text[boundary : boundary + 2] == "\n\n" else 1)
            content = text[start:end].strip()
            if content:
                # Trim whitespace from the provenance offsets without changing
                # the actual source text used for retrieval.
                left_trim = len(text[start:end]) - len(text[start:end].lstrip())
                right_trim = len(text[start:end].rstrip())
                yield content, start + left_trim, start + right_trim
            if end >= text_len:
                break
            next_start = max(start + 1, end - self.overlap)
            if next_start <= start:
                next_start = end
            start = next_start


def _file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _normalise_vector(vector: Sequence[float]) -> list[float]:
    values = [float(item) for item in vector]
    norm = math.sqrt(sum(item * item for item in values))
    return [item / norm for item in values] if norm else values


def _dot(left: Sequence[float], right: Sequence[float]) -> float:
    return sum(a * b for a, b in zip(left, right))


def _safe_fingerprint_value(value: Any) -> Any:
    """Convert a component option into deterministic JSON-compatible data.

    Fingerprints are persisted with the index and therefore must never include
    secrets (such as an API key) or process-specific object representations.
    Provider/parser adapters can expose a small ``fingerprint`` value; all
    other values are reduced to primitive/container forms and finally a stable
    type name.
    """

    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {
            str(key): _safe_fingerprint_value(item)
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        }
    if isinstance(value, (list, tuple, set, frozenset)):
        values = [_safe_fingerprint_value(item) for item in value]
        # Sets have no stable iteration order.  Sorting the JSON form keeps the
        # resulting digest independent of hash randomisation.
        if isinstance(value, (set, frozenset)):
            values.sort(key=lambda item: json.dumps(item, ensure_ascii=False, sort_keys=True, default=str))
        return values
    return f"{type(value).__module__}.{type(value).__qualname__}"


def _stable_fingerprint(value: Mapping[str, Any]) -> str:
    encoded = json.dumps(
        _safe_fingerprint_value(value),
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _qualified_name(value: Any) -> str:
    """Return a class/callable name without including object memory addresses."""

    module = getattr(value, "__module__", None)
    qualname = getattr(value, "__qualname__", None)
    if module and qualname:
        return f"{module}.{qualname}"
    cls = value if isinstance(value, type) else type(value)
    return f"{cls.__module__}.{cls.__qualname__}"


def _module_available(module_name: str) -> bool:
    try:
        return importlib.util.find_spec(module_name) is not None
    except (ImportError, AttributeError, ValueError):
        # ``find_spec`` can raise ValueError for a module already imported
        # without a spec (some test doubles and plugin loaders do this).
        return False


def _distribution_version(distribution: str) -> str | None:
    try:
        return importlib.metadata.version(distribution)
    except importlib.metadata.PackageNotFoundError:
        return None
    except Exception:
        return None


def _pdf_parser_descriptor() -> dict[str, Any]:
    """Describe parser backends available in the current Python environment.

    A PDF may have been indexed with a fallback parser (or left unparsed when
    no backend was installed).  Persisting both availability and package
    versions lets the next startup notice that a better parser was installed
    and refresh the affected chunks automatically.
    """

    backends = (
        ("fitz", "PyMuPDF", "pymupdf"),
        ("pypdf", "pypdf", "pypdf"),
        ("PyPDF2", "PyPDF2", "PyPDF2"),
    )
    return {
        "backends": [
            {
                "module": module,
                "distribution": distribution,
                "available": _module_available(module),
                "version": _distribution_version(distribution),
                "parser": parser_name,
            }
            for module, distribution, parser_name in backends
        ]
    }


class PersistentHybridIndex:
    """Persistent local hybrid index for TXT/PDF support documents.

    ``build`` performs an incremental rebuild based on SHA-256 fingerprints;
    ``rebuild`` always re-parses the source tree.  Both methods return a stats
    dictionary suitable for health/observability endpoints.
    """

    def __init__(
        self,
        root: Path,
        *,
        index_dir: Path | None = None,
        chunker: TextChunker | None = None,
        parser: DocumentParser | None = None,
        embedding_provider: EmbeddingProvider | Callable[[Sequence[str]], Sequence[Sequence[float]]] | None = None,
        extensions: Iterable[str] = DEFAULT_EXTENSIONS,
        # ``external`` is excluded by default because the repository's CSV
        # usage records are not knowledge documents.  Pass ``exclude_dirs=()``
        # when an embedding/indexing job intentionally wants every PDF/TXT.
        exclude_dirs: Iterable[str] = (".git", ".next", "node_modules", "external"),
        lexical_weight: float = 0.60,
        keyword_weight: float = 0.20,
        vector_weight: float = 0.20,
    ) -> None:
        self.root = Path(root).resolve()
        self.index_dir = Path(index_dir or (self.root / ".retrieval_index")).resolve()
        self.index_path = self.index_dir / "index.json"
        self.chunker = chunker or TextChunker()
        self.parser = parser or DocumentParser()
        self.embedding_provider = embedding_provider
        self.extensions = frozenset(
            item.lower() if str(item).startswith(".") else f".{str(item).lower()}" for item in extensions
        )
        self.exclude_dirs = frozenset(str(item) for item in exclude_dirs)
        if min(lexical_weight, keyword_weight, vector_weight) < 0:
            raise ValueError("retrieval weights cannot be negative")
        if lexical_weight + keyword_weight + vector_weight <= 0:
            raise ValueError("at least one retrieval weight must be positive")
        self.weights = (float(lexical_weight), float(keyword_weight), float(vector_weight))

        self.chunks: list[DocumentChunk] = []
        self._terms: list[Counter[str]] = []
        self._idf: dict[str, float] = {}
        self._vectors: list[dict[str, float]] = []
        self._dense_vectors: list[list[float]] = []
        self._files: dict[str, dict[str, Any]] = {}
        self._metadata: dict[str, Any] = {}
        self._loaded = False
        self.load()

    @property
    def ready(self) -> bool:
        return bool(self.chunks)

    @property
    def document_count(self) -> int:
        return len(self.chunks)

    @property
    def source_count(self) -> int:
        return len({chunk.source for chunk in self.chunks})

    def _config_descriptor(self) -> dict[str, Any]:
        """Return every option that changes indexed content or ranking.

        The descriptor is intentionally explicit rather than derived from
        ``__dict__`` so transient runtime state (loaded vectors, caches, API
        clients, etc.) cannot invalidate an otherwise reusable index.
        """

        return {
            "config_version": INDEX_CONFIG_VERSION,
            "index_version": INDEX_VERSION,
            "root": str(self.root),
            "extensions": sorted(self.extensions),
            "exclude_dirs": sorted(self.exclude_dirs),
            "chunker": {
                "class": _qualified_name(self.chunker),
                "chunk_size": int(self.chunker.chunk_size),
                "overlap": int(self.chunker.overlap),
                "min_chunk_size": int(self.chunker.min_chunk_size),
            },
            "weights": {
                "lexical": self.weights[0],
                "keyword": self.weights[1],
                "vector": self.weights[2],
            },
            # Tokenisation is part of the sparse and hash-vector index.  If its
            # rules change, this marker can be bumped independently of the JSON
            # storage format version.
            "tokenizer": "cjk-bigram-v1",
        }

    @staticmethod
    def _parser_descriptor(parser: Any) -> dict[str, Any]:
        descriptor: dict[str, Any] = {
            "class": _qualified_name(parser),
            "pdf": _pdf_parser_descriptor(),
        }
        custom = getattr(parser, "fingerprint", None)
        try:
            custom = custom() if callable(custom) else custom
        except Exception:
            custom = None
        if custom is not None:
            descriptor["custom"] = _safe_fingerprint_value(custom)
        return descriptor

    @staticmethod
    def _provider_descriptor(provider: Any) -> dict[str, Any]:
        if provider is None:
            return {"class": None, "configured": False}
        descriptor: dict[str, Any] = {"class": _qualified_name(provider)}
        # These fields cover all built-in providers while also giving common
        # custom adapters a useful invalidation signal.  API keys are
        # deliberately excluded; changing a key does not change the model
        # vectors and persisting it would be a credential leak.
        for name in (
            "model",
            "model_name",
            "dimensions",
            "dimension",
            "base_url",
            "batch_size",
            "timeout",
            "retries",
        ):
            try:
                value = getattr(provider, name)
            except Exception:
                continue
            if value is not None and not callable(value):
                descriptor[name] = _safe_fingerprint_value(value)
        try:
            configured = getattr(provider, "configured")
            if not callable(configured):
                descriptor["configured"] = bool(configured)
        except Exception:
            pass
        custom = getattr(provider, "fingerprint", None)
        try:
            custom = custom() if callable(custom) else custom
        except Exception:
            custom = None
        if custom is not None:
            descriptor["custom"] = _safe_fingerprint_value(custom)
        return descriptor

    def _current_fingerprints(self) -> dict[str, Any]:
        """Build non-secret fingerprints for the active index configuration."""

        config = self._config_descriptor()
        parser = self._parser_descriptor(self.parser)
        provider = self._provider_descriptor(self.embedding_provider)
        provider_fingerprint = _stable_fingerprint(provider)
        return {
            "config": config,
            "config_fingerprint": _stable_fingerprint(config),
            "parser": parser,
            "parser_fingerprint": _stable_fingerprint(parser),
            "provider": provider,
            "provider_fingerprint": provider_fingerprint,
            # ``embedding_*`` is an explicit alias for API/observability code;
            # retain ``provider_*`` for callers that use the generic term.
            "embedding": provider,
            "embedding_fingerprint": provider_fingerprint,
        }

    def _files_unchanged(self, fingerprints: Mapping[str, Mapping[str, Any]]) -> bool:
        if set(fingerprints) != set(self._files):
            return False
        fields = ("sha256", "size", "mtime_ns")
        for source, current in fingerprints.items():
            previous = self._files.get(source)
            if not isinstance(previous, Mapping):
                return False
            if any(previous.get(field) != current.get(field) for field in fields):
                return False
        return True

    def _iter_files(self) -> list[Path]:
        if not self.root.exists():
            return []
        paths: list[Path] = []
        for path in self.root.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in self.extensions:
                continue
            if any(part in self.exclude_dirs for part in path.relative_to(self.root).parts[:-1]):
                continue
            paths.append(path)
        return sorted(paths, key=lambda item: item.as_posix().lower())

    def _source_name(self, path: Path) -> str:
        try:
            return path.relative_to(self.root.parent).as_posix()
        except ValueError:
            return path.relative_to(self.root).as_posix()

    def load(self) -> bool:
        """Load a previously persisted index; return whether it succeeded."""

        if not self.index_path.exists():
            self._loaded = False
            return False
        try:
            data = json.loads(self.index_path.read_text(encoding="utf-8"))
            if int(data.get("version", -1)) != INDEX_VERSION:
                return False
            self.chunks = [DocumentChunk.from_dict(item) for item in data.get("chunks", [])]
            self._idf = {str(key): float(value) for key, value in (data.get("idf") or {}).items()}
            self._vectors = [
                {str(key): float(value) for key, value in (vector or {}).items()}
                for vector in data.get("vectors", [])
            ]
            self._dense_vectors = [
                [float(item) for item in vector] for vector in data.get("dense_vectors", [])
            ]
            raw_files = data.get("files") or {}
            if not isinstance(raw_files, Mapping):
                return False
            self._files = {
                str(key): dict(value)
                for key, value in raw_files.items()
                if isinstance(value, Mapping)
            }
            self._metadata = dict(data.get("metadata") or {})
            self._terms = [Counter(tokenize(chunk.content)) for chunk in self.chunks]
            if len(self._vectors) != len(self.chunks):
                self._vectors = []
            if len(self._dense_vectors) != len(self.chunks):
                self._dense_vectors = []
            self._loaded = True
            return True
        except (OSError, ValueError, TypeError, KeyError, json.JSONDecodeError):
            self._loaded = False
            return False

    def build(self, *, force: bool = False) -> dict[str, Any]:
        """Build or incrementally refresh the index and persist it atomically."""

        paths = self._iter_files()
        fingerprints: dict[str, dict[str, Any]] = {}
        for path in paths:
            relative = self._source_name(path)
            stat = path.stat()
            fingerprints[relative] = {
                "sha256": _file_hash(path),
                "size": stat.st_size,
                "mtime_ns": stat.st_mtime_ns,
            }

        current_fingerprints = self._current_fingerprints()
        metadata_compatible = self._loaded and all(
            self._metadata.get(key) == value
            for key, value in current_fingerprints.items()
            if key.endswith("_fingerprint")
        )
        unchanged = (
            not force
            and self._loaded
            and metadata_compatible
            and self._files_unchanged(fingerprints)
        )
        if unchanged:
            return self.stats(rebuilt=False)

        new_chunks: list[DocumentChunk] = []
        parse_errors: list[dict[str, str]] = []
        for path in paths:
            relative = self._source_name(path)
            file_info = fingerprints[relative]
            try:
                pages = self.parser.parse(path)
                title = path.stem
                chunks = self.chunker.chunk_pages(
                    pages,
                    source=relative,
                    file_hash=str(file_info["sha256"]),
                    title=title,
                )
                new_chunks.extend(chunks)
                file_info["pages"] = len(pages)
                file_info["chunks"] = len(chunks)
                if path.suffix.lower() == ".pdf" and not pages:
                    parse_errors.append(
                        {
                            "source": relative,
                            "error": "PDF 没有可提取文本；请安装 PyMuPDF/pypdf，或对扫描件先做 OCR",
                        }
                    )
            except Exception as exc:  # keep one bad document from blocking all others
                parse_errors.append({"source": relative, "error": str(exc)})
                file_info["pages"] = 0
                file_info["chunks"] = 0

        self.chunks = new_chunks
        self._files = fingerprints
        self._terms = [Counter(tokenize(chunk.content)) for chunk in self.chunks]
        self._build_sparse_vectors()
        self._build_dense_vectors()
        self._metadata = {
            "version": INDEX_VERSION,
            "built_at": _utc_now(),
            "root": str(self.root),
            "chunk_size": self.chunker.chunk_size,
            "overlap": self.chunker.overlap,
            "embedding_provider": type(self.embedding_provider).__name__ if self.embedding_provider else None,
            "parse_errors": parse_errors,
            **current_fingerprints,
        }
        self._persist()
        return self.stats(rebuilt=True)

    def rebuild(self) -> dict[str, Any]:
        return self.build(force=True)

    def _build_sparse_vectors(self) -> None:
        document_count = len(self._terms)
        frequencies: Counter[str] = Counter()
        for terms in self._terms:
            frequencies.update(terms.keys())
        self._idf = {
            term: math.log((1 + document_count) / (1 + count)) + 1.0
            for term, count in frequencies.items()
        }
        vectors: list[dict[str, float]] = []
        for terms in self._terms:
            if not terms:
                vectors.append({})
                continue
            total = sum(terms.values()) or 1
            vector = {term: (count / total) * self._idf.get(term, 1.0) for term, count in terms.items()}
            norm = math.sqrt(sum(value * value for value in vector.values()))
            vectors.append({term: value / norm for term, value in vector.items()} if norm else {})
        self._vectors = vectors

    def _embed_documents(self, texts: Sequence[str]) -> list[list[float]]:
        provider = self.embedding_provider
        if provider is None:
            return []
        try:
            method = getattr(provider, "embed_documents", None)
            if callable(method):
                vectors = method(texts)
            elif callable(provider):
                vectors = provider(texts)
            else:
                return []
            return [_normalise_vector(vector) for vector in vectors]
        except Exception:
            # Embeddings are an enhancement; lexical retrieval must still work
            # when a local model is unavailable or a remote call times out.
            return []

    def _embed_query(self, query: str) -> list[float]:
        provider = self.embedding_provider
        if provider is None:
            return []
        try:
            method = getattr(provider, "embed_query", None)
            if callable(method):
                return _normalise_vector(method(query))
            if callable(provider):
                vectors = provider([query])
                return _normalise_vector(vectors[0]) if vectors else []
        except Exception:
            pass
        return []

    def _build_dense_vectors(self) -> None:
        if self.embedding_provider is None or not self.chunks:
            self._dense_vectors = []
            return
        vectors = self._embed_documents([chunk.content for chunk in self.chunks])
        if len(vectors) != len(self.chunks):
            self._dense_vectors = []
            return
        dimensions = len(vectors[0]) if vectors else 0
        if not dimensions or any(len(vector) != dimensions for vector in vectors):
            self._dense_vectors = []
            return
        self._dense_vectors = vectors

    def _persist(self) -> None:
        self.index_dir.mkdir(parents=True, exist_ok=True)
        payload = {
            "version": INDEX_VERSION,
            "metadata": self._metadata,
            "files": self._files,
            "chunks": [chunk.as_dict() for chunk in self.chunks],
            "idf": self._idf,
            "vectors": self._vectors,
            "dense_vectors": self._dense_vectors,
        }
        # NamedTemporaryFile in the destination directory guarantees os.replace
        # is atomic on Windows as well as POSIX.
        fd, temporary = tempfile.mkstemp(prefix="index-", suffix=".tmp", dir=str(self.index_dir))
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
                json.dump(payload, handle, ensure_ascii=False, separators=(",", ":"))
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, self.index_path)
        finally:
            try:
                os.unlink(temporary)
            except FileNotFoundError:
                pass
        self._loaded = True

    def _query_sparse(self, query: str) -> tuple[Counter[str], dict[str, float], float]:
        terms = Counter(tokenize(query))
        if not terms:
            return terms, {}, 0.0
        total = sum(terms.values()) or 1
        vector = {term: (count / total) * self._idf.get(term, 1.0) for term, count in terms.items()}
        norm = math.sqrt(sum(value * value for value in vector.values()))
        if norm:
            vector = {term: value / norm for term, value in vector.items()}
        return terms, vector, norm

    @staticmethod
    def _keyword_score(query_terms: Counter[str], document_terms: Counter[str], content: str, query: str) -> float:
        if not query_terms or not document_terms:
            return 0.0
        query_set = set(query_terms)
        document_set = set(document_terms)
        coverage = len(query_set & document_set) / len(query_set)
        # Exact phrase/substring matches are high-signal for model numbers and
        # error codes, so add a bounded bonus.
        normal_query = re.sub(r"\s+", "", query.lower())
        normal_content = re.sub(r"\s+", "", content.lower())
        phrase_bonus = 0.25 if normal_query and normal_query in normal_content else 0.0
        return min(1.0, coverage + phrase_bonus)

    def search(
        self,
        query: str,
        *,
        top_k: int = 5,
        min_score: float = 0.0,
        metadata_filter: Mapping[str, Any] | Callable[[DocumentChunk], bool] | None = None,
        diversify_by_source: bool = False,
    ) -> list[RetrievalHit]:
        """Return ranked hits, highest score first.

        ``metadata_filter`` can be a mapping (all key/value pairs must match) or
        a predicate.  ``diversify_by_source`` keeps at most one hit per source;
        callers can use it when composing short LLM contexts.
        """

        if top_k <= 0 or not query.strip() or not self.chunks:
            return []
        if not self._vectors:
            self._terms = [Counter(tokenize(chunk.content)) for chunk in self.chunks]
            self._build_sparse_vectors()
        query_terms, query_vector, _ = self._query_sparse(query)
        # A function-word/punctuation-only query has no lexical signal.  Hash
        # embeddings still return a non-zero vector for any string (and can
        # therefore produce arbitrary low-score neighbours), so stop before
        # the dense layer is consulted.  This keeps both lexical and hybrid
        # modes consistent and avoids injecting unrelated context into the
        # answer prompt.
        if not query_terms:
            return []
        query_dense = self._embed_query(query) if self._dense_vectors else []
        lexical_weight, keyword_weight, vector_weight = self.weights
        active_vector = bool(query_dense and self._dense_vectors and len(query_dense) == len(self._dense_vectors[0]))
        if not active_vector:
            vector_weight = 0.0
        total_weight = lexical_weight + keyword_weight + vector_weight
        if total_weight <= 0:
            return []

        scored: list[RetrievalHit] = []
        seen_sources: set[str] = set()
        for index, chunk in enumerate(self.chunks):
            if isinstance(metadata_filter, Mapping):
                def _matches_filter(key: str, expected: Any) -> bool:
                    # Source/id are first-class chunk fields; all other keys
                    # resolve against parser-provided metadata.
                    actual = chunk.source if key == "source" else chunk.id if key in {"id", "chunk_id"} else chunk.metadata.get(key)
                    return actual == expected

                if any(not _matches_filter(str(key), value) for key, value in metadata_filter.items()):
                    continue
            if callable(metadata_filter) and not metadata_filter(chunk):
                continue
            terms = self._terms[index] if index < len(self._terms) else Counter(tokenize(chunk.content))
            lexical = _dot(
                [query_vector.get(term, 0.0) for term in query_vector],
                [self._vectors[index].get(term, 0.0) for term in query_vector],
            ) if index < len(self._vectors) else 0.0
            keyword = self._keyword_score(query_terms, terms, chunk.content, query)
            dense = _dot(query_dense, self._dense_vectors[index]) if active_vector else 0.0
            # Negative cosine is not evidence of relevance. In particular,
            # shifting cosine into [0, 1] would turn an orthogonal score of 0
            # into 0.5 and make unrelated hash-vector queries look relevant.
            dense = max(0.0, min(1.0, dense)) if active_vector else 0.0
            score = (lexical_weight * lexical + keyword_weight * keyword + vector_weight * dense) / total_weight
            if score < min_score or score <= 0:
                continue
            scored.append(
                RetrievalHit(
                    chunk=chunk,
                    score=score,
                    lexical_score=lexical,
                    keyword_score=keyword,
                    vector_score=dense,
                )
            )

        scored.sort(key=lambda hit: (-hit.score, -hit.lexical_score, hit.source, hit.id))
        selected: list[RetrievalHit] = []
        for hit in scored:
            if diversify_by_source and hit.source in seen_sources:
                continue
            seen_sources.add(hit.source)
            selected.append(hit)
            if len(selected) >= top_k:
                break
        return [
            RetrievalHit(
                chunk=hit.chunk,
                score=round(hit.score, 6),
                lexical_score=round(hit.lexical_score, 6),
                keyword_score=round(hit.keyword_score, 6),
                vector_score=round(hit.vector_score, 6),
                rank=rank,
            )
            for rank, hit in enumerate(selected, start=1)
        ]

    def context(
        self,
        query: str,
        *,
        top_k: int = 5,
        max_chars: int = 6000,
        metadata_filter: Mapping[str, Any] | Callable[[DocumentChunk], bool] | None = None,
        diversify_by_source: bool = False,
    ) -> tuple[str, list[RetrievalHit]]:
        """Build bounded, citation-labelled context for an LLM prompt."""

        # Keep the context contract explicit even if a custom ``search``
        # implementation is injected later.  Empty/stopword-only queries
        # should never yield arbitrary dense-vector context.
        if not query.strip() or not tokenize(query):
            return "", []

        hits = self.search(
            query,
            top_k=top_k,
            metadata_filter=metadata_filter,
            diversify_by_source=diversify_by_source,
        )
        sections: list[str] = []
        used = 0
        for hit in hits:
            section = f"[{hit.rank}] {hit.citation}\n{hit.content.strip()}"
            if used and used + len(section) + 2 > max_chars:
                break
            if len(section) > max_chars - used:
                section = section[: max_chars - used].rstrip() + "…"
            sections.append(section)
            used += len(section) + 2
        return "\n\n".join(sections), hits[: len(sections)]

    def stats(self, *, rebuilt: bool | None = None) -> dict[str, Any]:
        parse_errors = self._metadata.get("parse_errors", []) if self._metadata else []
        try:
            display_index_path = self.index_path.relative_to(self.root.parent).as_posix()
        except ValueError:
            # Runtime status should not disclose arbitrary host filesystem
            # paths when a caller configured the index outside the project.
            display_index_path = self.index_path.name
        result: dict[str, Any] = {
            "ready": self.ready,
            "chunks": len(self.chunks),
            "sources": self.source_count,
            "files": len(self._files),
            "vocabulary": len(self._idf),
            "dense_vectors": bool(self._dense_vectors),
            "index_path": display_index_path,
            "built_at": self._metadata.get("built_at"),
            "parse_errors": parse_errors,
        }
        for key in (
            "config_fingerprint",
            "parser_fingerprint",
            "provider_fingerprint",
            "embedding_fingerprint",
        ):
            if key in self._metadata:
                result[key] = self._metadata[key]
        if self._metadata.get("parser") is not None:
            result["parser"] = self._metadata["parser"]
        if self._metadata.get("provider") is not None:
            # The provider descriptor is safe to expose: it intentionally
            # excludes API keys and other credentials.
            result["provider"] = self._metadata["provider"]
        if rebuilt is not None:
            result["rebuilt"] = rebuilt
        return result


# Friendly aliases for callers that prefer shorter names.
HybridRetriever = PersistentHybridIndex
ProductionRetriever = PersistentHybridIndex


def build_knowledge_index(
    root: Path,
    *,
    index_dir: Path | None = None,
    embedding_provider: EmbeddingProvider | Callable[[Sequence[str]], Sequence[Sequence[float]]] | None = None,
    force: bool = False,
    **kwargs: Any,
) -> PersistentHybridIndex:
    """Create and build an index in one call.

    This convenience function is useful from a FastAPI lifespan hook or a
    command-line rebuild script::

        index = build_knowledge_index(settings.knowledge_path,
                                      index_dir=settings.project_root / ".retrieval_index")

    The returned object remains searchable and exposes ``stats()`` for health
    reporting.  ``kwargs`` are forwarded to :class:`PersistentHybridIndex`.
    """

    index = PersistentHybridIndex(
        root,
        index_dir=index_dir,
        embedding_provider=embedding_provider,
        **kwargs,
    )
    index.build(force=force)
    return index


__all__ = [
    "DocumentChunk",
    "DocumentParser",
    "DashScopeEmbeddingProvider",
    "EmbeddingProvider",
    "build_knowledge_index",
    "HashEmbeddingProvider",
    "HybridRetriever",
    "PageText",
    "PersistentHybridIndex",
    "ProductionRetriever",
    "RetrievalHit",
    "SentenceTransformerProvider",
    "TextChunker",
    "tokenize",
]
